import turtle
turtle.color("red")

turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)

turtle.penup()
turtle.left(90)
turtle.goto(50,0)
turtle.pendown()
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)

turtle.penup()
turtle.left(90)
turtle.goto(0,-50)
turtle.pendown()
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)

turtle.penup()
turtle.left(90)
turtle.goto(50,-50)
turtle.pendown()
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)